# Generated by Django 3.0.7 on 2021-04-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=30)),
                ('groupID', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgtext', models.CharField(max_length=1000)),
                ('msgID', models.IntegerField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chatID', models.ManyToManyField(to='mariachatapp.User')),
                ('groupID', models.ManyToManyField(to='mariachatapp.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='username',
            field=models.ManyToManyField(to='mariachatapp.User'),
        ),
    ]
